######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 17:45:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console

# Input
HEADERS += a.h \
  b.h \
  c.h 

SOURCES += a.cpp \
  b.cpp \
  c.cpp \
 test.cpp
